### ISSUE TITLE
Exotic hashes that don't load or look particularly wrong with the current build

### ISSUE THREAD

**Issue by chrisfried** [lowlines/three-tgx-loader#1]
D1:
255654879
1758882169
3742521821
57660786
4100639362
4100639365
4100639364
1623420384

D2:
1345867570
2907129557
3089417789
1345867571
1508896098

**Comment by chrisfried** [comment]
Ships that don't load.

D1:
2245431200
2245431201
2245431207
2615360546
3011919237
3206937312
3808257331
3926270234

D2:
2503134037
838210459
3213307847
2503134032
2503134038
2503134039
2503134036
2503134042
838210457
838210456
3213307849 // These last two didn't load on the old build, either.
3213307848

**Comment by lowlines** [comment]
Interesting. Having a look at the Zhalo Supercell and it has 2 lockedDyes with the same slotTypeIndex. The way Spasm resolved gear dyes was to override them by slotTypeIndex, but that must be wrong.

**Comment by lowlines** [comment]
Just pushed an update. All those hashes should now load.

- The loader now exposes more hidden geometry than it previously did which includes FX geometry that I have no figured out how to filter/render properly out yet.
- The specular strength on D1 items is probably using the wrong data resulting in some models having a light mask kind of effect.
- The Verona Mesh and High Line D2 ships appear to have a vertexBuffer loading issue that results in missing vertices. Will need to look into this.
